- hosts: all 
  vars_files:
    -  vars/{{ ansible_facts['distribution'] }}.yml
  tasks:
    - name: "Installing Software"
      package:
              name: "{{ software_name }}"
    
    - name: "Starting Services"
      service:
              name: "{{ software_name }}"
              state: started

    - name: "Deploying WebPages"
      copy:
              src: files/{{ ansible_facts['distribution'] }}.html
              dest: "/var/www/html"

